import { resourceUrl } from '../platform/build';
export const ASSET_IDS = [
  'food-orange',
  'food-pear',
  'food-peach',
  'food-strawberry',
  'food-grape',
  'food-watermelon',
  'food-mango',
  'food-pineapple',
  'food-cucumber',
  'food-carrot',
  'food-potato',
  'food-corn',
  'food-broccoli',
  'food-mushroom',
  'food-pumpkin',
  'food-pea',
  'food-rice',
  'food-noodles',
  'food-egg',
  'food-chicken',
  'food-beef',
  'food-fish',
  'food-tofu',
  'food-milk',
  'food-yogurt',
  'food-butter',
  'food-cream',
  'food-vanilla',
  'food-chocolate',
  'food-honey',
  'food-jam',
  'food-coconut',
  'food-raisin',
  'food-smoothie',
  'food-milkshake',
  'food-pizza',
  'food-salad',
  'food-cake',
  'food-cookie',

  'cat-idle',
  'cat-read',
  'cat-reach',
  'cat-carry',
  'cat-place',
  'cat-greet',
  'cat-blocked',
  'cat-celebrate',
  'cat-step-0',
  'cat-step-1',
  'cat-step-2',
  'cat-step-3',
  'bread',
  'cheese',
  'lettuce',
  'tomato',
  'bun',
  'patty',
  'cooked-patty',
  'cone',
  'vanilla',
  'strawberry',
  'sandwich',
  'burger',
  'banana-juice',
  'salad-sandwich',
  'cheese-burger',
  'ice-station',
  'board-station',
  'grill-station',
  'vanilla-cone',
  'strawberry-cup',
  'double-cream',
  'banana-cream',
  'market',
  'apple',
  'banana',
  'cup',
  'juice',
  'machine',
  'tray',
  'guest-0-0',
  'guest-0-1',
  'guest-0-2',
  'guest-1-0',
  'guest-1-1',
  'guest-1-2',
] as const;
export const assetUrl = (id: string) => resourceUrl('assets', `${id}.webp`);

export const CORE_ASSETS = ASSET_IDS.filter(
  (id) =>
    id.startsWith('cat-') ||
    id.startsWith('guest-') ||
    ['market', 'tray', 'machine', 'apple', 'banana', 'cup', 'juice'].includes(id),
);
