import { resourceUrl } from '../platform/build';
export const ASSET_IDS = [
  'cat-idle',
  'cat-read',
  'cat-reach',
  'cat-carry',
  'cat-place',
  'cat-greet',
  'cat-blocked',
  'cat-celebrate',
  'market',
  'apple',
  'banana',
  'cup',
  'juice',
  'machine',
  'tray',
  'guest-0-0',
  'guest-0-1',
  'guest-0-2',
  'guest-1-0',
  'guest-1-1',
  'guest-1-2',
] as const;
export const assetUrl = (id: string) => resourceUrl('assets', `${id}.webp`);
