import type { RequestId } from './catalog';
export type CourseKind = 'listen' | 'pair' | 'spell' | 'quantity' | 'sentence' | 'review';
export type CourseFoundation = 'new' | 'letters' | 'phrases';
export interface MiniLevel {
  id: string;
  kind: CourseKind;
  theme: string;
  title: string;
  goal: string;
  scene: string;
  foundation: CourseFoundation;
  targets: readonly string[];
  pool: readonly string[];
  support: string;
  completion: string;
  taskKinds?: readonly Exclude<CourseKind, 'review'>[];
  pools?: readonly (readonly string[])[];
}
/** Six authored scenes per mechanic. Task count belongs to the level, not the engine. */
export const MINI_LEVELS: readonly MiniLevel[] = [
  {
    id: 'listen-fruit-hello',
    kind: 'listen',
    theme: '水果篮',
    title: '早晨认识水果',
    goal: '听到名字，找到水果',
    scene: '大咪在开店前整理水果篮。',
    foundation: 'new',
    targets: ['apple', 'banana', 'orange', 'pear'],
    pool: ['apple', 'banana', 'orange', 'pear'],
    support: '图片与重听',
    completion: '四种水果都找到了',
  },
  {
    id: 'listen-fruit-picnic',
    kind: 'listen',
    theme: '水果篮',
    title: '野餐篮里有什么',
    goal: '听词找不同的水果',
    scene: '兔兔把野餐水果摆在桌上。',
    foundation: 'new',
    targets: ['peach', 'grape', 'watermelon', 'mango', 'pineapple'],
    pool: ['peach', 'grape', 'watermelon', 'mango', 'pineapple'],
    support: '图片与重听',
    completion: '野餐水果摆好了',
  },
  {
    id: 'listen-garden',
    kind: 'listen',
    theme: '菜园篮',
    title: '菜园来客',
    goal: '分辨菜园食物的声音',
    scene: '刺刺从菜园带来不同颜色。',
    foundation: 'new',
    targets: ['cucumber', 'carrot', 'corn', 'broccoli', 'mushroom'],
    pool: ['cucumber', 'carrot', 'corn', 'broccoli', 'mushroom'],
    support: '图片与重听',
    completion: '菜园篮收好了',
  },
  {
    id: 'listen-kitchen',
    kind: 'listen',
    theme: '厨房篮',
    title: '厨房材料',
    goal: '听到材料再指一指',
    scene: '长辈把厨房材料排在柜台。',
    foundation: 'new',
    targets: ['bread', 'cheese', 'egg', 'rice', 'noodles'],
    pool: ['bread', 'cheese', 'egg', 'rice', 'noodles'],
    support: '图片与重听',
    completion: '厨房材料认清了',
  },
  {
    id: 'listen-sweet',
    kind: 'listen',
    theme: '香甜篮',
    title: '甜甜的味道',
    goal: '听音找香甜配料',
    scene: '冰淇淋台旁有不同香味。',
    foundation: 'new',
    targets: ['chocolate', 'honey', 'jam', 'coconut', 'raisin'],
    pool: ['chocolate', 'honey', 'jam', 'coconut', 'raisin'],
    support: '图片与重听',
    completion: '配料瓶摆好了',
  },
  {
    id: 'listen-ready',
    kind: 'listen',
    theme: '点心篮',
    title: '小食会点心',
    goal: '听词找到可供应的点心',
    scene: '小食会前，大咪点数成品。',
    foundation: 'new',
    targets: ['milk', 'yogurt', 'pizza', 'salad', 'cake', 'cookie'],
    pool: ['milk', 'yogurt', 'pizza', 'salad', 'cake', 'cookie'],
    support: '图片与重听',
    completion: '小食会点心排好了',
  },
  {
    id: 'pair-fruit',
    kind: 'pair',
    theme: '水果篮',
    title: '水果标签成组配',
    goal: '把四张声音标签配到图片',
    scene: '兔兔帮忙贴水果篮标签。',
    foundation: 'new',
    targets: ['apple', 'pear', 'peach', 'banana'],
    pool: ['apple', 'pear', 'peach', 'banana'],
    support: '可重听；用过的图片留作记录',
    completion: '四张标签配好了',
  },
  {
    id: 'pair-garden',
    kind: 'pair',
    theme: '菜园篮',
    title: '菜园成组配',
    goal: '一组接一组配菜园图片',
    scene: '刺刺要把菜园篮交给长辈。',
    foundation: 'new',
    targets: ['tomato', 'lettuce', 'carrot', 'cucumber', 'corn'],
    pool: ['tomato', 'lettuce', 'carrot', 'cucumber', 'corn'],
    support: '可重听；已配的图片保留',
    completion: '菜园标签配好了',
  },
  {
    id: 'pair-meal',
    kind: 'pair',
    theme: '厨房篮',
    title: '餐车材料成组配',
    goal: '配出材料和声音',
    scene: '大咪检查今天要用的材料。',
    foundation: 'new',
    targets: ['bread', 'bun', 'cheese', 'rice'],
    pool: ['bread', 'bun', 'cheese', 'rice'],
    support: '图片、中文和重听',
    completion: '材料有了位置',
  },
  {
    id: 'pair-flavor',
    kind: 'pair',
    theme: '香甜篮',
    title: '香味成组配',
    goal: '区别冰淇淋口味和配料',
    scene: '兔兔想帮忙整理冰淇淋台。',
    foundation: 'new',
    targets: ['vanilla', 'strawberry', 'banana', 'chocolate', 'honey'],
    pool: ['vanilla', 'strawberry', 'banana', 'chocolate', 'honey'],
    support: '图片、中文和重听',
    completion: '口味与配料分清了',
  },
  {
    id: 'pair-drinks',
    kind: 'pair',
    theme: '饮品',
    title: '饮品成组配',
    goal: '配对不同饮品',
    scene: '长辈把饮品单交给大咪。',
    foundation: 'new',
    targets: ['juice', 'smoothie', 'milk', 'yogurt'],
    pool: ['juice', 'smoothie', 'milk', 'yogurt'],
    support: '图片和重听',
    completion: '饮品单配好了',
  },
  {
    id: 'pair-community',
    kind: 'pair',
    theme: '社区小食会',
    title: '朋友喜欢的食物',
    goal: '把小食会食物与声音配好',
    scene: '朋友们要把桌上的食物认清。',
    foundation: 'new',
    targets: ['sandwich', 'burger', 'cake', 'cookie', 'salad'],
    pool: ['sandwich', 'burger', 'cake', 'cookie', 'salad'],
    support: '图片和重听',
    completion: '桌上的食物配好了',
  },
  {
    id: 'spell-short-fruit',
    kind: 'spell',
    theme: '水果篮',
    title: '短短的水果词',
    goal: '用独立字母拼出食物名',
    scene: '给水果箱写简单标签。',
    foundation: 'letters',
    targets: ['apple', 'pear', 'peach', 'grape'],
    pool: ['apple', 'pear', 'peach', 'grape'],
    support: '先看图；可看词样；字母可撤回',
    completion: '水果标签写好了',
  },
  {
    id: 'spell-garden',
    kind: 'spell',
    theme: '菜园篮',
    title: '菜园标签',
    goal: '拼出菜园物品名',
    scene: '刺刺想留下菜园的英文标签。',
    foundation: 'letters',
    targets: ['corn', 'pea', 'tomato', 'carrot'],
    pool: ['corn', 'pea', 'tomato', 'carrot'],
    support: '词样、图片、撤回',
    completion: '菜园标签写好了',
  },
  {
    id: 'spell-kitchen',
    kind: 'spell',
    theme: '厨房篮',
    title: '厨房便签',
    goal: '拼厨房材料的词',
    scene: '大咪要把材料归位。',
    foundation: 'letters',
    targets: ['bread', 'cheese', 'egg', 'rice'],
    pool: ['bread', 'cheese', 'egg', 'rice'],
    support: '词样、图片、撤回',
    completion: '厨房便签写好了',
  },
  {
    id: 'spell-sweet',
    kind: 'spell',
    theme: '香甜篮',
    title: '香甜配料便签',
    goal: '拼熟悉的配料名',
    scene: '冰淇淋台的瓶子需要标签。',
    foundation: 'letters',
    targets: ['honey', 'jam', 'cream', 'chocolate'],
    pool: ['honey', 'jam', 'cream', 'chocolate'],
    support: '词样、图片、撤回',
    completion: '配料便签写好了',
  },
  {
    id: 'spell-drink',
    kind: 'spell',
    theme: '饮品',
    title: '饮品标签',
    goal: '拼饮品和杯子的词',
    scene: '长辈把饮品写上黑板。',
    foundation: 'letters',
    targets: ['milk', 'juice', 'yogurt', 'smoothie'],
    pool: ['milk', 'juice', 'yogurt', 'smoothie'],
    support: '词样、图片、撤回',
    completion: '饮品黑板写好了',
  },
  {
    id: 'spell-snack',
    kind: 'spell',
    theme: '点心篮',
    title: '点心标签',
    goal: '拼小食会点心名',
    scene: '朋友们需要找到自己的点心。',
    foundation: 'letters',
    targets: ['cake', 'cookie', 'pizza', 'salad'],
    pool: ['cake', 'cookie', 'pizza', 'salad'],
    support: '词样、图片、撤回',
    completion: '点心标签写好了',
  },
  {
    id: 'quantity-one-two',
    kind: 'quantity',
    theme: '数量',
    title: '一个还是两个',
    goal: '听请求辨别份数',
    scene: '兔兔和刺刺要的苹果数不同。',
    foundation: 'new',
    targets: ['apple', 'two', 'banana', 'fruit'],
    pool: ['apple', 'two', 'banana', 'fruit'],
    support: '请求图片与重听',
    completion: '份数分清了',
  },
  {
    id: 'quantity-fruit-mix',
    kind: 'quantity',
    theme: '组合',
    title: '水果组合',
    goal: '辨别单份与两种水果',
    scene: '野餐篮要分别装水果。',
    foundation: 'new',
    targets: ['fruit', 'apple', 'banana', 'two'],
    pool: ['fruit', 'apple', 'banana', 'two'],
    support: '图片可对照',
    completion: '水果组合排好了',
  },
  {
    id: 'quantity-drinks',
    kind: 'quantity',
    theme: '饮品',
    title: '哪杯果汁',
    goal: '区别苹果汁、香蕉汁和水果',
    scene: '两位朋友都带着杯子来。',
    foundation: 'new',
    targets: ['juice', 'banana-juice', 'apple', 'banana'],
    pool: ['juice', 'banana-juice', 'apple', 'banana'],
    support: '请求图片与重听',
    completion: '果汁请求找到了',
  },
  {
    id: 'quantity-ice',
    kind: 'quantity',
    theme: '冰淇淋',
    title: '一球与双球',
    goal: '辨别容器、口味和球数',
    scene: '树荫下每位朋友要的不一样。',
    foundation: 'new',
    targets: ['vanilla-cup', 'vanilla-cone', 'strawberry-cup', 'double-cream'],
    pool: ['vanilla-cup', 'vanilla-cone', 'strawberry-cup', 'double-cream'],
    support: '图片可对照；不要求拼写',
    completion: '冰淇淋请求分清了',
  },
  {
    id: 'quantity-layers',
    kind: 'quantity',
    theme: '野餐',
    title: '夹层和搭配',
    goal: '按内容选三明治与搭配',
    scene: '野餐前大家检查篮子。',
    foundation: 'new',
    targets: ['sandwich', 'salad-sandwich', 'fruit', 'juice'],
    pool: ['sandwich', 'salad-sandwich', 'fruit', 'juice'],
    support: '请求图片与重听',
    completion: '野餐篮检查好了',
  },
  {
    id: 'quantity-burger',
    kind: 'quantity',
    theme: '黄昏',
    title: '汉堡夹层',
    goal: '辨别芝士与蔬菜汉堡',
    scene: '黄昏来了两位客人。',
    foundation: 'new',
    targets: ['burger', 'cheese-burger', 'sandwich', 'salad-sandwich'],
    pool: ['burger', 'cheese-burger', 'sandwich', 'salad-sandwich'],
    support: '请求图片与重听',
    completion: '汉堡夹层分清了',
  },
  {
    id: 'sentence-first-request',
    kind: 'sentence',
    theme: '请求便签',
    title: '请给我一个',
    goal: '用词块表达单份水果',
    scene: '大咪帮兔兔整理请求便签。',
    foundation: 'phrases',
    targets: ['apple', 'banana', 'apple', 'banana'],
    pool: ['apple', 'banana', 'two', 'fruit'],
    support: '先看图；词块可撤回；可看例句',
    completion: '单份请求说清了',
  },
  {
    id: 'sentence-two',
    kind: 'sentence',
    theme: '请求便签',
    title: '两个苹果',
    goal: '数量和复数一起表达',
    scene: '长辈想给两位朋友各一个苹果。',
    foundation: 'phrases',
    targets: ['two', 'apple', 'two', 'banana'],
    pool: ['apple', 'banana', 'two', 'fruit'],
    support: '图示份数；词块可撤回',
    completion: '数量请求说清了',
  },
  {
    id: 'sentence-and',
    kind: 'sentence',
    theme: '请求便签',
    title: '还有一个',
    goal: '用 and 连起两种水果',
    scene: '野餐篮想同时放苹果和香蕉。',
    foundation: 'phrases',
    targets: ['fruit', 'apple', 'fruit', 'banana'],
    pool: ['apple', 'banana', 'two', 'fruit'],
    support: '图示组合；词块可撤回',
    completion: '组合请求说清了',
  },
  {
    id: 'sentence-drink',
    kind: 'sentence',
    theme: '请求便签',
    title: '想喝什么',
    goal: '表达两种果汁',
    scene: '饮品便签要交给大咪。',
    foundation: 'phrases',
    targets: ['juice', 'banana-juice', 'juice', 'banana-juice'],
    pool: ['juice', 'banana-juice', 'apple', 'banana'],
    support: '果汁图片与例句',
    completion: '饮品请求说清了',
  },
  {
    id: 'sentence-ice',
    kind: 'sentence',
    theme: '请求便签',
    title: '杯子或蛋筒',
    goal: '表达不同容器的冰淇淋',
    scene: '树荫下的请求要写在便签上。',
    foundation: 'phrases',
    targets: ['vanilla-cup', 'vanilla-cone', 'strawberry-cup', 'double-cream'],
    pool: ['vanilla-cup', 'vanilla-cone', 'strawberry-cup', 'double-cream'],
    support: '图片与例句；词块可撤回',
    completion: '冰淇淋便签写好了',
  },
  {
    id: 'sentence-meals',
    kind: 'sentence',
    theme: '请求便签',
    title: '野餐和黄昏',
    goal: '表达两种三明治与两种汉堡',
    scene: '小食会前，大咪整理大家的便签。',
    foundation: 'phrases',
    targets: ['sandwich', 'salad-sandwich', 'burger', 'cheese-burger'],
    pool: ['sandwich', 'salad-sandwich', 'burger', 'cheese-burger'],
    support: '图片与例句；词块可撤回',
    completion: '小食会便签写好了',
  },
  {
    id: 'mixed-review',
    kind: 'review',
    theme: '回访练习',
    title: '小院混合复习',
    goal: '听、配、拼、辨数量、组句各试一次',
    scene: '长辈请大咪整理五种旧便签，看看哪些还想再练。',
    foundation: 'phrases',
    targets: ['apple', 'pear', 'cheese', 'two', 'fruit'],
    pool: [],
    taskKinds: ['listen', 'pair', 'spell', 'quantity', 'sentence'],
    pools: [
      ['apple', 'banana', 'orange', 'pear'],
      ['pear', 'peach', 'apple', 'banana'],
      [],
      ['apple', 'two', 'banana', 'fruit'],
      [],
    ],
    support: '每项都先看图；读写可选',
    completion: '五种练习都回访了',
  },
];
export const miniLevel = (id: string) => MINI_LEVELS.find((level) => level.id === id);
export const miniRequest = (id: string): id is RequestId =>
  [
    'apple',
    'banana',
    'two',
    'fruit',
    'juice',
    'banana-juice',
    'vanilla-cup',
    'vanilla-cone',
    'strawberry-cup',
    'double-cream',
    'sandwich',
    'salad-sandwich',
    'burger',
    'cheese-burger',
  ].includes(id);
