export const FOOD = {
  apple: ['苹果', 'apple'],
  banana: ['香蕉', 'banana'],
  cup: ['空杯', 'cup'],
  juice: ['苹果汁', 'apple juice'],
  'banana-juice': ['香蕉汁', 'banana juice'],
  bread: ['面包', 'bread'],
  cheese: ['芝士', 'cheese'],
  lettuce: ['生菜', 'lettuce'],
  tomato: ['番茄', 'tomato'],
  bun: ['圆面包', 'bun'],
  patty: ['生饼', 'patty'],
  'cooked-patty': ['熟饼', 'cooked patty'],
  cone: ['蛋筒', 'cone'],
  vanilla: ['香草球', 'vanilla'],
  strawberry: ['草莓球', 'strawberry'],
  'vanilla-cone': ['香草蛋筒', 'vanilla ice cream'],
  'strawberry-cup': ['草莓冰淇淋杯', 'strawberry ice cream'],
  'double-cream': ['双球冰淇淋', 'two scoops of ice cream'],
  'banana-cream': ['香蕉冰淇淋', 'ice cream with banana'],
  sandwich: ['芝士三明治', 'cheese sandwich'],
  'salad-sandwich': ['蔬菜三明治', 'lettuce and tomato sandwich'],
  burger: ['汉堡', 'burger'],
  'cheese-burger': ['芝士汉堡', 'cheeseburger'],
  orange: ['橙子', 'orange'],
  pear: ['梨', 'pear'],
  peach: ['桃子', 'peach'],
  'fresh-strawberry': ['草莓', 'strawberry'],
  grape: ['葡萄', 'grape'],
  watermelon: ['西瓜', 'watermelon'],
  mango: ['芒果', 'mango'],
  pineapple: ['菠萝', 'pineapple'],
  cucumber: ['黄瓜', 'cucumber'],
  carrot: ['胡萝卜', 'carrot'],
  potato: ['土豆', 'potato'],
  corn: ['玉米', 'corn'],
  broccoli: ['西兰花', 'broccoli'],
  mushroom: ['蘑菇', 'mushroom'],
  pumpkin: ['南瓜', 'pumpkin'],
  pea: ['豌豆', 'pea'],
  rice: ['米饭', 'rice'],
  noodles: ['面条', 'noodles'],
  egg: ['鸡蛋', 'egg'],
  chicken: ['鸡肉', 'chicken'],
  beef: ['牛肉', 'beef'],
  fish: ['鱼肉', 'fish'],
  tofu: ['豆腐', 'tofu'],
  milk: ['牛奶', 'milk'],
  yogurt: ['酸奶', 'yogurt'],
  butter: ['黄油', 'butter'],
  cream: ['奶油', 'cream'],
  'vanilla-pod': ['香草', 'vanilla'],
  chocolate: ['巧克力', 'chocolate'],
  honey: ['蜂蜜', 'honey'],
  jam: ['果酱', 'jam'],
  coconut: ['椰子', 'coconut'],
  raisin: ['葡萄干', 'raisin'],
  smoothie: ['思慕雪', 'smoothie'],
  milkshake: ['奶昔', 'milkshake'],
  pizza: ['比萨饼', 'pizza'],
  salad: ['沙拉', 'salad'],
  cake: ['蛋糕', 'cake'],
  cookie: ['曲奇饼干', 'cookie'],
} as const;
export type Product = keyof typeof FOOD;
export type Family = 'juice' | 'ice' | 'sandwich' | 'burger' | 'ready';
export type StationId = 'ice' | 'board' | 'grill';
export interface Recipe {
  id: string;
  family: Family;
  station: 'machine' | StationId;
  inputs: readonly Product[];
  output: Product;
  ms: number;
  action: string;
}
export const RECIPES: readonly Recipe[] = [
  {
    id: 'juice',
    family: 'juice',
    station: 'machine',
    inputs: ['apple', 'cup'],
    output: 'juice',
    ms: 5000,
    action: '榨汁',
  },
  {
    id: 'banana-juice',
    family: 'juice',
    station: 'machine',
    inputs: ['banana', 'cup'],
    output: 'banana-juice',
    ms: 5000,
    action: '榨汁',
  },
  {
    id: 'vanilla-cone',
    family: 'ice',
    station: 'ice',
    inputs: ['cone', 'vanilla'],
    output: 'vanilla-cone',
    ms: 1000,
    action: '接好冰淇淋',
  },
  {
    id: 'strawberry-cup',
    family: 'ice',
    station: 'ice',
    inputs: ['cup', 'strawberry'],
    output: 'strawberry-cup',
    ms: 1000,
    action: '接好冰淇淋',
  },
  {
    id: 'double-cream',
    family: 'ice',
    station: 'ice',
    inputs: ['cup', 'vanilla', 'strawberry'],
    output: 'double-cream',
    ms: 1300,
    action: '接好双球',
  },
  {
    id: 'banana-cream',
    family: 'ice',
    station: 'ice',
    inputs: ['cup', 'vanilla', 'banana'],
    output: 'banana-cream',
    ms: 1300,
    action: '装好配料',
  },
  {
    id: 'sandwich',
    family: 'sandwich',
    station: 'board',
    inputs: ['bread', 'bread', 'cheese'],
    output: 'sandwich',
    ms: 1200,
    action: '盖合',
  },
  {
    id: 'salad-sandwich',
    family: 'sandwich',
    station: 'board',
    inputs: ['bread', 'bread', 'lettuce', 'tomato'],
    output: 'salad-sandwich',
    ms: 1200,
    action: '盖合',
  },
  {
    id: 'patty',
    family: 'burger',
    station: 'grill',
    inputs: ['patty'],
    output: 'cooked-patty',
    ms: 3500,
    action: '煎好饼',
  },
  {
    id: 'burger',
    family: 'burger',
    station: 'board',
    inputs: ['bun', 'cooked-patty', 'lettuce', 'tomato'],
    output: 'burger',
    ms: 1200,
    action: '盖好汉堡',
  },
  {
    id: 'cheese-burger',
    family: 'burger',
    station: 'board',
    inputs: ['bun', 'cooked-patty', 'cheese'],
    output: 'cheese-burger',
    ms: 1200,
    action: '盖好汉堡',
  },
];
export const sameContents = (a: readonly Product[], b: readonly Product[]) =>
  a.length === b.length && [...a].sort().join('|') === [...b].sort().join('|');
export const recipeFor = (station: Recipe['station'], products: readonly Product[]) =>
  RECIPES.find((r) => r.station === station && sameContents(products, r.inputs));
export const RAW: readonly Product[] = [
  'apple',
  'banana',
  'orange',
  'pear',
  'peach',
  'fresh-strawberry',
  'grape',
  'watermelon',
  'mango',
  'pineapple',
  'cup',
  'bread',
  'cheese',
  'lettuce',
  'tomato',
  'bun',
  'patty',
  'cone',
  'vanilla',
  'strawberry',
];
export const PREPARED: readonly Product[] = [
  'milk',
  'yogurt',
  'smoothie',
  'milkshake',
  'pizza',
  'salad',
  'cake',
  'cookie',
];
export const isFinished = (product: Product) => !RAW.includes(product);
export const FAMILY_SUPPLIES: Record<Family, readonly Product[]> = {
  ready: ['orange', 'pear', 'peach', 'milk', 'cookie'],
  juice: ['apple', 'banana', 'cup'],
  ice: ['cone', 'cup', 'vanilla', 'strawberry', 'banana'],
  sandwich: ['bread', 'cheese', 'lettuce', 'tomato'],
  burger: ['bun', 'patty', 'cheese', 'lettuce', 'tomato'],
};
export const FAMILY_STATIONS: Record<Family, readonly StationId[]> = {
  ready: [],
  juice: [],
  ice: ['ice'],
  sandwich: ['board'],
  burger: ['grill', 'board'],
};
export const foodAsset = (product: Product): string => FOOD_OBJECT_ASSETS[product] ?? product;
const FOOD_OBJECT_ASSETS: Partial<Record<Product, string>> = {
  apple: 'apple',
  banana: 'banana',
  orange: 'food-orange',
  pear: 'food-pear',
  peach: 'food-peach',
  'fresh-strawberry': 'food-strawberry',
  grape: 'food-grape',
  watermelon: 'food-watermelon',
  mango: 'food-mango',
  pineapple: 'food-pineapple',
  tomato: 'tomato',
  cucumber: 'food-cucumber',
  carrot: 'food-carrot',
  potato: 'food-potato',
  lettuce: 'lettuce',
  corn: 'food-corn',
  broccoli: 'food-broccoli',
  mushroom: 'food-mushroom',
  pumpkin: 'food-pumpkin',
  pea: 'food-pea',
  bread: 'bread',
  bun: 'bun',
  rice: 'food-rice',
  noodles: 'food-noodles',
  egg: 'food-egg',
  chicken: 'food-chicken',
  beef: 'food-beef',
  fish: 'food-fish',
  cheese: 'cheese',
  tofu: 'food-tofu',
  milk: 'food-milk',
  yogurt: 'food-yogurt',
  butter: 'food-butter',
  cream: 'food-cream',
  'vanilla-pod': 'food-vanilla',
  chocolate: 'food-chocolate',
  honey: 'food-honey',
  jam: 'food-jam',
  coconut: 'food-coconut',
  raisin: 'food-raisin',
  juice: 'juice',
  smoothie: 'food-smoothie',
  milkshake: 'food-milkshake',
  'vanilla-cone': 'vanilla-cone',
  sandwich: 'sandwich',
  burger: 'burger',
  pizza: 'food-pizza',
  salad: 'food-salad',
  cake: 'food-cake',
  cookie: 'food-cookie',
};

export const SUPPLY_PAGES: readonly (readonly Product[])[] = [
  ['orange', 'pear', 'peach', 'fresh-strawberry'],
  ['grape', 'watermelon', 'mango', 'pineapple'],
  ['milk', 'yogurt', 'smoothie', 'milkshake'],
  ['pizza', 'salad', 'cake', 'cookie'],
];
export const suppliesFor = (session: { family: Family; supplyPage: number }) =>
  session.family === 'ready'
    ? (SUPPLY_PAGES[session.supplyPage] ?? SUPPLY_PAGES[0] ?? [])
    : FAMILY_SUPPLIES[session.family];
