import type { RequestId } from './catalog';

export interface StoryLevel {
  id: string;
  chapter: number;
  title: string;
  who: string;
  situation: string;
  objective: string;
  result: string;
  requests: readonly RequestId[];
  choice?: {
    prompt: string;
    labels: readonly [string, string];
    alternate: readonly RequestId[];
    responses: readonly [string, string];
  };
}
/** Stable chapter and level IDs. Each service has a concrete customer need and a visible outcome. */
export const STORY_LEVELS: readonly StoryLevel[] = [
  {
    id: 'c1-open-door',
    chapter: 0,
    title: '第一次开门',
    who: '兔兔',
    situation: '长辈把钥匙交给大咪。兔兔来买熟悉的苹果。',
    objective: '听请求，把苹果放盘并交给兔兔。',
    result: '兔兔说：明天我还会来。',
    requests: ['apple'],
  },
  {
    id: 'c1-first-juice',
    chapter: 0,
    title: '老食谱的第一页',
    who: '刺刺',
    situation: '刺刺带来长辈旧食谱的第一页。',
    objective: '按旧食谱榨一杯苹果汁。',
    result: '刺刺记起长辈说过：小院需要一朵花。',
    requests: ['juice'],
  },
  {
    id: 'c1-new-fruit',
    chapter: 0,
    title: '换一种水果',
    who: '兔兔',
    situation: '兔兔回来了，想尝昨天没选的香蕉。',
    objective: '把香蕉直接装盘；食物先和声音见面。',
    result: '兔兔发现试新味道也很开心。',
    requests: ['banana'],
  },
  {
    id: 'c1-two-friends',
    chapter: 0,
    title: '两位朋友',
    who: '兔兔与刺刺',
    situation: '两位朋友同时来，一位想要混合水果，一位想喝香蕉汁。',
    objective: '决定先招呼谁，再完成两份不同请求。',
    result: '先被照顾的朋友帮另一位拿住了花盆。',
    requests: ['fruit', 'banana-juice'],
    choice: {
      prompt: '先帮谁？',
      labels: ['先帮兔兔准备水果', '先帮刺刺榨香蕉汁'],
      alternate: ['banana-juice', 'fruit'],
      responses: ['兔兔先把水果接好，等刺刺的果汁。', '刺刺先喝上果汁，再帮兔兔拿水果。'],
    },
  },
  {
    id: 'c1-window-flower',
    chapter: 0,
    title: '窗台的小花',
    who: '长辈与兔兔',
    situation: '兔兔带来一盆小花，长辈看着第一天的营业。',
    objective: '准备两只苹果和一杯果汁，招呼新朋友。',
    result: '小花放上窗台。旧食谱夹着一张写着“树荫”的纸条。',
    requests: ['two', 'juice'],
  },
  {
    id: 'c2-cup',
    chapter: 1,
    title: '树荫下的杯子',
    who: '兔兔',
    situation: '兔兔带着同伴回来，想用杯子接一球香草。',
    objective: '选杯、一球香草、制作并送出。',
    result: '兔兔说：原来杯装也很好拿。',
    requests: ['vanilla-cup'],
  },
  {
    id: 'c2-cone',
    chapter: 1,
    title: '蛋筒的声音',
    who: '刺刺',
    situation: '刺刺喜欢边走边吃，想拿蛋筒。',
    objective: '选蛋筒和香草，做完后交给刺刺。',
    result: '刺刺指着树上的彩旗，说还缺一角。',
    requests: ['vanilla-cone'],
  },
  {
    id: 'c2-flavor',
    chapter: 1,
    title: '不一样的口味',
    who: '兔兔',
    situation: '树荫下，兔兔这次想试草莓味。',
    objective: '杯装不变，改选草莓球。',
    result: '兔兔记住了自己选的新味道。',
    requests: ['strawberry-cup'],
  },
  {
    id: 'c2-two-scoops',
    chapter: 1,
    title: '一球再一球',
    who: '刺刺',
    situation: '刺刺要请同伴，想把两种味道放在同一杯。',
    objective: '杯中放香草和草莓两球，明确制作。',
    result: '刺刺把彩旗系在树荫旁。',
    requests: ['double-cream'],
  },
  {
    id: 'c2-topping',
    chapter: 1,
    title: '旗子下面',
    who: '兔兔与刺刺',
    situation: '彩旗挂好了。两位朋友的要求仍然不同。',
    objective: '做香蕉配料冰淇淋，再做蛋筒；先后由你安排。',
    result: '彩旗留在小院。兔兔说下次要带野餐篮。',
    requests: ['banana-cream', 'vanilla-cone'],
  },
  {
    id: 'c3-bread',
    chapter: 2,
    title: '野餐篮打开了',
    who: '兔兔',
    situation: '兔兔带来篮子，想把芝士夹进面包。',
    objective: '准备两片面包和芝士，盖合三明治。',
    result: '兔兔在树下找到了野餐的位置。',
    requests: ['sandwich'],
  },
  {
    id: 'c3-garden',
    chapter: 2,
    title: '菜园里的颜色',
    who: '刺刺',
    situation: '刺刺带来生菜和番茄，想试另一种夹层。',
    objective: '用两片面包、生菜和番茄做三明治。',
    result: '刺刺想把这份带给正在布置小院的长辈。',
    requests: ['salad-sandwich'],
  },
  {
    id: 'c3-drink',
    chapter: 2,
    title: '野餐还缺一杯',
    who: '兔兔与长辈',
    situation: '三明治快好了，长辈还想要一杯果汁。',
    objective: '分别安排三明治和果汁；等待加工时可准备另一盘。',
    result: '长辈铺开一角旧桌布，留给大家坐。',
    requests: ['sandwich', 'juice'],
  },
  {
    id: 'c3-extra',
    chapter: 2,
    title: '再带一份水果',
    who: '刺刺',
    situation: '刺刺在开工前补充野餐需要的水果，不改变已接订单。',
    objective: '把蔬菜三明治与混合水果分别送好。',
    result: '刺刺帮兔兔把野餐篮放上桌。',
    requests: ['salad-sandwich', 'fruit'],
  },
  {
    id: 'c3-tablecloth',
    chapter: 2,
    title: '旧桌布的新位置',
    who: '兔兔与刺刺',
    situation: '大家想试两种夹层。旧桌布刚好铺满小院桌子。',
    objective: '完成两份不同三明治，安排托盘。',
    result: '桌布留在小院。长辈说黄昏会有人带灯来。',
    requests: ['sandwich', 'salad-sandwich'],
  },
  {
    id: 'c4-grill',
    chapter: 3,
    title: '煎台点亮了',
    who: '刺刺',
    situation: '黄昏，刺刺想吃一个有生菜和番茄的汉堡。',
    objective: '煎熟肉饼，再与面包和蔬菜组装。',
    result: '刺刺说香味让路过的朋友停了下来。',
    requests: ['burger'],
  },
  {
    id: 'c4-cheese',
    chapter: 3,
    title: '芝士的那份',
    who: '兔兔',
    situation: '兔兔想吃芝士汉堡，和刺刺的夹层不同。',
    objective: '煎饼后换芝士组装。',
    result: '兔兔帮忙把第一盏小灯挂起来。',
    requests: ['cheese-burger'],
  },
  {
    id: 'c4-wait',
    chapter: 3,
    title: '煎饼的时候',
    who: '刺刺与长辈',
    situation: '肉饼在煎台上，长辈也想要一个苹果。',
    objective: '煎饼等待时可给另一盘准备苹果。',
    result: '长辈说：你已经会安排厨房了。',
    requests: ['burger', 'apple'],
  },
  {
    id: 'c4-two-boards',
    chapter: 3,
    title: '先做哪一份',
    who: '兔兔与刺刺',
    situation: '有人想吃芝士汉堡，也有人要三明治。',
    objective: '选择先准备哪一份，并让煎台和组合板衔接。',
    result: '先拿到食物的朋友帮另一位摆好餐具。',
    requests: ['cheese-burger', 'sandwich'],
    choice: {
      prompt: '先安排哪份？',
      labels: ['先煎汉堡肉饼', '先准备三明治'],
      alternate: ['sandwich', 'cheese-burger'],
      responses: ['兔兔在等煎饼时摆好了餐具。', '刺刺先拿到三明治，也帮兔兔看着煎台。'],
    },
  },
  {
    id: 'c4-lights',
    chapter: 3,
    title: '灯串亮了',
    who: '兔兔与刺刺',
    situation: '老朋友带着灯串回来，还想各要一份汉堡。',
    objective: '分清两种夹层，完成双客服务。',
    result: '灯亮时，朋友们说出了秘密：欢迎大咪第一次独立开店。大咪决定办小食会。',
    requests: ['burger', 'cheese-burger'],
  },
  {
    id: 'c5-invite',
    chapter: 4,
    title: '大咪发出邀请',
    who: '大咪与长辈',
    situation: '大咪翻开旧食谱未写完的“社区小食会”一页，主动邀请邻居。',
    objective: '先给帮忙的朋友准备果汁和水果。',
    result: '长辈把笔交给大咪：最后一页由你来写。',
    requests: ['juice', 'fruit'],
  },
  {
    id: 'c5-arrivals',
    chapter: 4,
    title: '桌布和彩旗',
    who: '兔兔与刺刺',
    situation: '兔兔带着彩旗，刺刺铺好桌布。',
    objective: '为两位朋友分别准备冰淇淋和三明治。',
    result: '小院的花、彩旗和桌布都回到了朋友身边。',
    requests: ['vanilla-cup', 'sandwich'],
  },
  {
    id: 'c5-help',
    chapter: 4,
    title: '灯光下的协作',
    who: '长辈与兔兔',
    situation: '灯串亮了，长辈看着煎台，兔兔摆好杯子。',
    objective: '等待肉饼时准备香蕉汁，或先做另一份。',
    result: '大咪把准备顺序安排清楚，长辈放心坐下。',
    requests: ['cheese-burger', 'banana-juice'],
  },
  {
    id: 'c5-everyone',
    chapter: 4,
    title: '每个人都不一样',
    who: '刺刺与兔兔',
    situation: '朋友们有各自喜欢的口味与搭配。',
    objective: '完成双球冰淇淋和蔬菜三明治，分给对应客人。',
    result: '兔兔想起第一次只敢要苹果，笑着说今天想试更多。',
    requests: ['double-cream', 'salad-sandwich'],
  },
  {
    id: 'c5-last-page',
    chapter: 4,
    title: '食谱最后一页',
    who: '大咪与所有朋友',
    situation: '旧食谱的最后一页还空着。小院里花、彩旗、桌布与灯都齐了。',
    objective: '由大咪亲手完成最后的汉堡、果汁和蛋筒交付。',
    result: '大咪写下“朋友们喜欢的味道”。长辈与兔兔、刺刺一起合影，小食会开场了。',
    requests: ['burger', 'juice', 'vanilla-cone'],
  },
];
export const storyLevel = (id: string | undefined) => STORY_LEVELS.find((level) => level.id === id);
export const levelsForChapter = (chapter: number) =>
  STORY_LEVELS.filter((level) => level.chapter === chapter);
export const storyRequests = (level: StoryLevel, choice: 0 | 1 = 0) =>
  choice === 1 && level.choice ? level.choice.alternate : level.requests;
